#pragma once
#define _USE_MATH_DEFINES
#include <cstdint>
#include <string>
#include <vector>
#include <cmath>
#include <istream>
#include <sstream>
#include <functional>
#include <map>
#include <algorithm>
#include <memory>